### ISSUE TITLE
[首先感谢up主]Centos上运行有点小问题，不知道为什么

### ISSUE THREAD

**Issue by liaux** [PomeloFoundation/YuukoBlog#1]
The LINQ expression 'Count()' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.

**Comment by yukozh** [comment]
This is a warning, not error
